server:
  port: 9090


spring:
  application:
    name: mytest
  mandatory-file-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true


myConfig:
  myObject:
    myName: 李四
    myAge: 25